codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        branches: null

    patch:
      default:
        target: auto
        threshold: 1%
        branches: null

    changes: false

  ignore: null

comment: false
  #layout: "header, diff, changes, sunburst, uncovered, tree"
  #branches: null
  #behavior: default
