branches:
    only: 
        - master

language: python

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
    # Non-pip dependency for cffi
    - sudo apt-get install -y libffi-dev

    # Add appropriate directories to various paths.
    - export PYHOME=$HOME/virtualenv/python${TRAVIS_PYTHON_VERSION}
    - export PYTHONPATH=$PYHOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH
    - export PATH=$HOME/bin:$PYHOME/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH

install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt   # Extra packages only needed for testing:

cache:
    - pip: true

script: 
    - python setup.py install --prefix=$PYHOME
    - cd tests
    - nosetests -v --with-coverage --cover-package=coord
    # Only do doctests on one version, since number of digits output varies between python 2 and 3
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then nosetests -v --with-coverage --cover-package=coord --with-doctest --where=../coord; fi

after_success:
    - codecov
