branches:
    only: 
        - master

language: python

python:
    - 2.7
    - 3.4
    - 3.5

before_install:
    - sudo apt-get install -y libffi-dev
    - export PYTHONPATH=$HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH

install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt   # Extra packages only needed for testing:

cache:
    - pip: true

script: 
    - python setup.py install --prefix=$HOME
    - cd tests
    - nosetests -v --with-coverage --cover-package=treecorr --with-doctest

after_success:
    - codecov
