name: Coord CI

on:
    push:
        branches:
            - main
            - releases/*

    pull_request:
        branches:
            - main
            - releases/*
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}

        env:
            CC: ${{ matrix.CC }}
            CXX: ${{ matrix.CXX }}

        strategy:
            matrix:
                # First all python versions in basic linux
                os: [ ubuntu-latest ]
                py: [ 2.7, 3.7, 3.8, 3.9, "3.10", pypy3 ]
                CC: [ gcc ]
                CXX: [ g++ ]

                # Add some other particular combinations to test
                include:
                    # One in MacOS
                    - os: macos-latest
                      py: 3.9

                    # Check one with clang compiler
                    - os: ubuntu-latest
                      py: 3.8

                    # Check one with gcc-11
                    - os: ubuntu-latest
                      py: 3.9

                    # Check one on Windows
                    - os: windows-latest
                      py: 3.9

        steps:
            - uses: actions/checkout@v2
              with:
                # Helpful for a reliable codecov upload.
                fetch-depth: 0

            - name: Set up Python ${{ matrix.py }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.py }}

            - name: Cache pip
              uses: actions/cache@v2
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-${{ matrix.py }}-pip-${{ hashFiles('requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-${{ matrix.py }}-pip-
                    ${{ runner.os }}-

            - name: Install basic dependencies
              run: |
                python -m pip install -U pip

                # Do this first to clarify potential conflicts
                pip install -U numpy

                # Standard dependencies
                pip install -U -r requirements.txt

                # Extra packages needed for testing
                pip install -U nose codecov coverage pytest astropy

            - name: List all installed packages for reference
              run: pip list

            - name: Build
              run: pip install -vvv .

            - name: Run unit tests
              run: |
                cd tests
                coverage run -m pytest -v
                cd ..  # N.B. This seems to happen automatically if omitted.
                       # Less confusing to include it explicitly.

            - name: Upload coverage to codecov
              if: matrix.os == 'ubuntu-latest'
              #uses: codecov/codecov-action@v1  # This didn't work for me.
              run: |
                cd tests
                pwd -P
                ls -la
                coverage combine || true  # (Not necessary I think, but just in case.)
                coverage report
                ls -la
                #codecov  # This also didn't work.
                # cf. https://community.codecov.io/t/github-not-getting-codecov-report-after-switching-from-travis-to-github-actions-for-ci/
                # The solution was to switch to the bash uploader line instead.
                bash <(curl -s https://codecov.io/bash)
                cd ..
